<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8d0500a5-f9df-4744-b117-063bffa3958a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Quanlycongviec.Application\Quanlycongviec.Application.csproj" />
    <ProjectReference Include="..\Quanlycongviec.Infrastructure\Quanlycongviec.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="..\..\scripts\seed_database.sql" CopyToOutputDirectory="PreserveNewest" Link="scripts\seed_database.sql" />
  </ItemGroup>

</Project>
